[package]
name = "aoc_2019_solution_9"
version = "0.1.0"
authors = ["benjaminch <benjamin.chastanier@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../../libs/intcode"  }
